services:
  dirsrv:
    hostname: dirsrv
    container_name: dirsrv
    ports:
      # See: https://github.com/389ds/389-ds-base/issues/6122
      - "7389:3389"
      - "3636:3636"
    environment:
      DS_DM_PASSWORD: password
      DS_SUFFIX_NAME: dc=example,dc=com
      DS_BACKEND_NAME: example
    volumes:
      - ./scripts/example/initdb.d:/container-entrypoint-initdb.d
